a, b = 12, 6.345
c, d = 'welcome', 'PYTHON'
print("The value of a =", a)
print('Type of variables a is : ', type(a))
print("The value of b =", b)
print('Type of variables b is : ', type(b))
print('Type of variables c is : ', type(c))
a, b = float(a), int(b)
print("\nThe value of a =", a)
print('Type of variables a is : ', type(a))
print("The value of b =", b)
print('Type of variables b is : ', type(b))
print("\nThe value of c =", c)
print("c[0:3]",c[0:3]," c[3:7]",c[3:7])
print("c[:4]",c[:4])
print("c[0]",c[0])
print("length of string c :",len(c))
print("Capitalizing c :",c.capitalize())
print("Uppercase of string c :",c.upper())
print("Lowercase of string d :",d.lower())
print("Reversing the string c :",c[::-1])
print("c[-2::-2] =", c[-2::-2])
print("Count of character 'e' :",c.count('e'))
print("c.find('e') =",c.find('e'))
print("c.find('e',2,7) =",c.find('e',2,len(c)))